config/routes.rb
Ticketmaster::Application.routes.draw do
  resources :ticket_histories

  

  
  resources :projects do
    resources :tickets
  end

  
  devise_for :users

   root :to => "projects#index"

end

app/models/ticket_history.rb
class TicketHistory < ActiveRecord::Base
  belongs_to :ticket
end

app/controllers/ticket_histories_controller.rb
class TicketHistoriesController < ApplicationController
  # GET /ticket_histories
  # GET /ticket_histories.xml
  def index
    @ticket_histories = TicketHistory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ticket_histories }
    end
  end

  # GET /ticket_histories/1
  # GET /ticket_histories/1.xml
  def show
    @ticket_history = TicketHistory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ticket_history }
    end
  end

  # GET /ticket_histories/new
  # GET /ticket_histories/new.xml
  def new
    @ticket_history = TicketHistory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ticket_history }
    end
  end

  # GET /ticket_histories/1/edit
  def edit
    @ticket_history = TicketHistory.find(params[:id])
  end

  # POST /ticket_histories
  # POST /ticket_histories.xml
  def create
    @ticket_history = TicketHistory.new(params[:ticket_history])
    @ticket = Ticket.find(@ticket_history.ticket_id)
    if params[:user_id] != "---"
      @ticket_history.extra_info = "extra stuff"
    end
    respond_to do |format|
      if @ticket_history.save
        format.html { redirect_to(project_tickets_path(@ticket.project_id), :notice => 'Ticket was successfully created.') }
        format.xml  { render :xml => @ticket, :status => :created, :location => @ticket }
      else
        format.html { redirect_to(project_ticket_path(@ticket.project_id, @ticket)) }
        format.xml  { render :xml => @ticket_history.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ticket_histories/1
  # PUT /ticket_histories/1.xml
  def update
    @ticket_history = TicketHistory.find(params[:id])

    respond_to do |format|
      if @ticket_history.update_attributes(params[:ticket_history])
        format.html { redirect_to(@ticket_history, :notice => 'Ticket history was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ticket_history.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_histories/1
  # DELETE /ticket_histories/1.xml
  def destroy
    @ticket_history = TicketHistory.find(params[:id])
    @ticket_history.destroy

    respond_to do |format|
      format.html { redirect_to(ticket_histories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/ticket_histories_helper.rb
module TicketHistoriesHelper
end

app/views/ticket_histories/_form.html.erb
<%= form_for(@ticket_history) do |f| %>
  <% if @ticket_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket_history.errors.count, "error") %> prohibited this ticket_history from being saved:</h2>

      <ul>
      <% @ticket_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticket_id %><br />
    <%= f.text_field :ticket_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :action %><br />
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :extra_info %><br />
    <%= f.text_field :extra_info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ticket_histories/edit.html.erb
<h1>Editing ticket_history</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket_history %> |
<%= link_to 'Back', ticket_histories_path %>

app/views/ticket_histories/index.html.erb
<h1>Listing ticket_histories</h1>

<table>
  <tr>
    <th>Ticket</th>
    <th>User</th>
    <th>Comment</th>
    <th>Action</th>
    <th>Extra info</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ticket_histories.each do |ticket_history| %>
  <tr>
    <td><%= ticket_history.ticket_id %></td>
    <td><%= ticket_history.user_id %></td>
    <td><%= ticket_history.comment %></td>
    <td><%= ticket_history.action %></td>
    <td><%= ticket_history.extra_info %></td>
    <td><%= link_to 'Show', ticket_history %></td>
    <td><%= link_to 'Edit', edit_ticket_history_path(ticket_history) %></td>
    <td><%= link_to 'Destroy', ticket_history, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket history', new_ticket_history_path %>

app/views/ticket_histories/new.html.erb
<h1>New ticket_history</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_histories_path %>

app/views/ticket_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ticket:</b>
  <%= @ticket_history.ticket_id %>
</p>

<p>
  <b>User:</b>
  <%= @ticket_history.user_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @ticket_history.comment %>
</p>

<p>
  <b>Action:</b>
  <%= @ticket_history.action %>
</p>

<p>
  <b>Extra info:</b>
  <%= @ticket_history.extra_info %>
</p>


<%= link_to 'Edit', edit_ticket_history_path(@ticket_history) %> |
<%= link_to 'Back', ticket_histories_path %>