config/routes.rb
Ticketmaster::Application.routes.draw do
  resources :ticket_histories

  

  
  resources :projects do
    resources :tickets
  end

  
  devise_for :users

   root :to => "projects#index"

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  has_many :ticket_histories
  validates_presence_of :description
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :init_controller
  # GET /tickets
  # GET /tickets.xml
  def index
    @tickets = Ticket.where({ :project_id => @project.id })


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.xml
  def show
    @ticket = Ticket.find(params[:id])
    @project = Project.find(@ticket.project_id)
    #@ticketHistories = TicketHistory.where({ :ticket_id => params[:id] })
    @ticketHistories = @ticket.ticket_histories
    @ticket_history = TicketHistory.new
    @ticket_history.ticket_id = @ticket.id
    
    #user = User.all
    #@users_array = user.map { |user| [user.email, user.id] }

    @users_array = @project.users.map { |user| [user.email, user.id] }
    @users_array =   ["---"] | @users_array

    #@users_hash = Hash.new(user.map {|u| [u.id, u.email]})
    #@users_hash = Hash[*user.map{|u| [u.id, u.email]}.flatten]
    @users_hash = get_all_users_hash

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.xml
  def new
    @ticket = Ticket.new
    @users_array = User.all.map { |user| [user.email, user.id] }

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
    @users_array = User.all.map { |user| [user.email, user.id] }

  end

  # POST /tickets
  # POST /tickets.xml
  def create
    @ticket = Ticket.new(params[:ticket])
    @ticket.project_id = params[:project_id]
    @project = Project.find(@ticket.project_id)
    @ticket.created_by_user_id = current_user.id
    @users_array = User.all.map { |user| [user.email, user.id] }

    respond_to do |format|
      if @ticket.save
        #format.html { redirect_to(project_tickets_path(@ticket.project_id), :notice => 'Ticket was successfully created.') }
        format.html { redirect_to(project_path(@project), :notice => 'Ticket was successfully created.') }
        format.xml  { render :xml => @ticket, :status => :created, :location => @ticket }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ticket.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.xml
  def update
    @ticket = Ticket.find(params[:id])
    @users_array = User.all.map { |user| [user.email, user.id] }

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to(project_ticket_path(@ticket.project_id, @ticket), :notice => 'Ticket was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html  do
          render :action => "edit"
        end
        format.xml  { render :xml => @ticket.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.xml
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html do
        redirect_to project_tickets_path(@project), :notice => "Ticket deleted successfully."
      end
      format.xml  { head :ok }
    end
  end

  private

  def init_controller
    @project = Project.find params[:project_id]
    @priorities = { :low => 0, :medium => 1, :high =>2 }.freeze
    @actions =  { :Resolved => 0, :Working_as_designed => 1, :Cannot_recreate =>2 }.freeze
  end

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket, :url => @ticket.new_record? ? project_tickets_path(@project) : project_ticket_path(@project, @ticket)) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= select(:ticket, :priority, @priorities) %>
  </div>
  <div class="field">
    <%= f.label :assigned_to_user_id %><br />
    <%= select(:ticket, :assigned_to_user_id, @users_array) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/_ticketHistory.html.erb
<table>
  <tr>
    <th>Comment</th>
    <th>Action</th>
    <th>Extra info</th>
  </tr>
<% @ticketHistories.each do |ticketHistory| %>
  <tr>
   <td><%= ticketHistory.comment %></td>
   <td><%= ticketHistory.action %></td>
   <td><%= ticketHistory.extra_info %></td>
  </tr>
<% end %>
</table>


<%= form_for(@ticket_history, :url => ticket_histories_path) do |f| %>
<%=  hidden_field(:ticket_history, :ticket_id)%>
<div class="field">
   <%= f.label :comment %><br />
   <%= f.text_field :comment %>
</div>

<div class="field">
   <%= f.label :action %><br />
   <%= select(:ticket_history, :action, @actions) %>
</div>
<div class="field">
    <%= f.label :assigned_to_user_id %><br />
    <%= select_tag(:user_id, options_for_select(@users_array)) %>
</div>
 <div class="actions">
    <%= f.submit %>
  </div>
<%end%>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>


<%= link_to 'Back', project_ticket_path(@project,@ticket) %> 

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<% unless notice.nil? %>
  <p id="notice"><%= notice %></p>
<% end %>

<table>
  <tr>
    <th>Title</th>
    <th>Project</th>
    <th>Created by user</th>
    <th>Status</th>
    <th>Assigned to user</th>
    <th>Priority</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.title %></td>
    <td><%= ticket.project_id %></td>
    <td><%= ticket.created_by_user_id %></td>
    <td><%= ticket.status %></td>
    <td><%= ticket.assigned_to_user_id %></td>
    <td><%= ticket.priority %></td>
    <td><%= ticket.description %></td>
    <td><%= link_to 'Show', project_ticket_path(@project, ticket) %></td>
    <td><%= link_to 'Edit', edit_project_ticket_path(@project, ticket) %></td>
    <td><%= link_to 'Destroy', project_ticket_path(@project, ticket), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_project_ticket_path(@project) %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= form_for(@ticket, :url => project_tickets_path(@project)) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= select(:ticket, :priority, @priorities) %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :assigned_to_user_id %><br />
    <%= select(:ticket, :assigned_to_user_id, @users_array) %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', @project %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @ticket.title %>
</p>

<p>
  <b>Project:</b>
  <%= @project.name %>
</p>

<p>
  <b>Created by user:</b>
  <%= @users_hash[@ticket.created_by_user_id] %>
</p>

<p>
  <b>Status:</b>
  <%= get_key(ticket_status, @ticket.status) %>
</p>

<p>
  <b>Assigned to user:</b>
  <%= @users_hash[@ticket.assigned_to_user_id] %>
</p>

<p>
  <b>Priority:</b>
  <%= get_key(priorities, @ticket.priority) %>
</p>

<p>
  <b>Description:</b>
  <%= @ticket.description %>
</p>

<%= render 'ticketHistory' %>

<%= link_to 'Edit', edit_project_ticket_path(@project, @ticket) %> |

<%#= link_to 'Back', project_tickets_path(@project) %> 
<%= link_to 'Back', @project %>