config/routes.rb
Ticketmaster::Application.routes.draw do
  resources :ticket_histories

  

  
  resources :projects do
    resources :tickets
  end

  
  devise_for :users

   root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :tickets
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    @ticket = Ticket.new

    @users_hash = get_all_users_hash

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @users = User.find(:all)
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    @users = User.find(:all)
  end

  # POST /projects
  # POST /projects.xml
  def create
    params[:project][:user_ids] ||= []
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    params[:project][:user_ids] ||= []
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_enabled %><br />
    <%= f.check_box :is_enabled %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <%= render :partial => "users", :locals => { users: @users, project: @project } %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_users.html.erb
 <% for user in @users %>
    <div>
      <%= check_box_tag "project[user_ids][]", user.id, @project.users.include?(user) %>
      <%= user.email %>
    </div>
  <% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Is enabled</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.is_enabled %></td>
    <td><%= project.start_date %></td>
    <td><%= project.end_date %></td>
    <td><%= project.description %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Is enabled:</b>
  <%= @project.is_enabled %>
</p>

<p>
  <b>Start date:</b>
  <%= @project.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @project.end_date %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<table>
  <tr>
    <th>title</th>
    <th>Created by</th>
    <th>Created at</th>
    <th>Status</th>
    <th>Assigned to</th>
    <th>Priority</th>
    <th></th>
  </tr>
<% @project.tickets.each do |ticket| %>
  <tr>
   <td><%= ticket.title %></td>
   <td><%= @users_hash[ticket.created_by_user_id] %></td>
   <td><%= date_format(ticket.created_at) %></td>
   <td><%= get_key(ticket_status, ticket.status) %></td>
   <td><%= @users_hash[ticket.assigned_to_user_id] %></td>
   <td><%= get_key(priorities, @ticket.priority) %></td>
   <td><%= link_to 'Show', project_ticket_path(@project, ticket) %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %> |
<%= link_to 'New Ticket', new_project_ticket_path(@project) %> 